/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define VIAL_KEYBOARD_UID {0xC5, 0xE1, 0x2A, 0x9B, 0x4F, 0x37, 0xD0, 0x8E}

#define VIAL_INSECURE

#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_RAINBOW_SWIRL
#define RGBLIGHT_DEFAULT_SPD 2
#define RGBLIGHT_DEFAULT_VAL 48
#define RGBLIGHT_HUE_STEP 4
